# Generated by Django 5.2 on 2025-05-14 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docshandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'managed': True},
        ),
    ]
