# Generated by Django 5.2 on 2025-05-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docshandler', '0002_alter_document_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
    ]
